# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"tweet_text": "00_core.ipynb",
         "check_secret": "00_core.ipynb",
         "run_server": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/fastwebhook/"

git_url = "https://github.com/fastai/fastwebhook/tree/master/"

def custom_doc_links(name): return None
